# Generated by Django 3.2 on 2021-05-03 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Priv', 'private'), ('Busi', 'business')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
